# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veiculos', '0004_auto_20170213_0344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculos',
            name='data_revisao',
            field=models.DateField(verbose_name='Data da ultima revisão (DD/MM/YYYY)'),
        ),
    ]
