# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 02:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cpf',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='CPF'),
        ),
    ]
