# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 03:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0003_auto_20170212_0312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoafisica',
            name='cep',
            field=models.CharField(max_length=8, null=True, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='pessoafisica',
            name='cpf',
            field=models.CharField(max_length=12, unique=True, verbose_name='CPF'),
        ),
    ]
