# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 02:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dependencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_dependencia', models.CharField(max_length=60, verbose_name='Nome da dependência')),
                ('identificacao', models.CharField(max_length=14, verbose_name='Identificação da dependência')),
                ('area', models.CharField(max_length=4)),
                ('situacao', models.CharField(max_length=60)),
                ('data_inclusao', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
