# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 04:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipamentos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100, unique=True, verbose_name='Código do equipamento')),
                ('nome', models.CharField(max_length=30, verbose_name='Nome do equipamento')),
                ('modelo', models.CharField(max_length=100, verbose_name='Modelo do veículo')),
                ('estado_fisico', models.CharField(blank=True, choices=[('D', 'Disponível'), ('R', 'Reservado'), ('E', 'Em manutenção')], max_length=2)),
                ('data_aquisicao', models.DateField(verbose_name='Data da ultima revisão (DD/MM/YYYY)')),
                ('obeservacao', models.TextField(max_length=100, verbose_name='Obersações sobre o equipamento')),
            ],
        ),
    ]
